# Generated by Django 5.2.6 on 2025-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_partner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('MODERATOR', 'Moderator'), ('DOCTOR', 'Doctor'), ('PARTNER', 'Partner'), ('PREMIUM', 'Premium')], default='STANDARD', max_length=20),
        ),
    ]
