# Generated by Django 5.2.6 on 2025-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstruation_date', models.DateField()),
                ('avg_cycle_duration', models.IntegerField(choices=[('22 DAYS', 22), ('23 DAYS', 23), ('24 DAYS', 24), ('25 DAYS', 25), ('26 DAYS', 26), ('27 DAYS', 27), ('28 DAYS', 28), ('29 DAYS', 29), ('30 DAYS', 30), ('31 DAYS', 31), ('32 DAYS', 32), ('33 DAYS', 33), ('34 DAYS', 34), ('35 DAYS', 35), ('36 DAYS', 36), ('37 DAYS', 37), ('38 DAYS', 38), ('39 DAYS', 39), ('40 DAYS', 40), ('41 DAYS', 41), ('42 DAYS', 42), ('43 DAYS', 43), ('44 DAYS', 44)])),
                ('avg_menstruation_duration', models.IntegerField(choices=[('1 DAY', 1), ('2 DAYS', 2), ('3 DAYS', 3), ('4 DAYS', 4), ('5 DAYS', 5), ('6 DAYS', 6), ('7 DAYS', 7), ('8 DAYS', 8), ('9 DAYS', 9), ('10 DAYS', 10)])),
            ],
        ),
    ]
