# Generated by Django 5.2.6 on 2025-09-22 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menstruation_start', models.DateField(default=django.utils.timezone.now)),
                ('menstruation_end', models.DateField(default=django.utils.timezone.now)),
                ('min_ovulation_window', models.DateField()),
                ('max_ovulation_window', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='cycledetails',
            name='avg_cycle_duration',
            field=models.IntegerField(choices=[(22, '22 DAYS'), (23, '23 DAYS'), (24, '24 DAYS'), (25, '25 DAYS'), (26, '26 DAYS'), (27, '27 DAYS'), (28, '28 DAYS'), (29, '29 DAYS'), (30, '30 DAYS'), (31, '31 DAYS'), (32, '32 DAYS'), (33, '33 DAYS'), (34, '34 DAYS'), (35, '35 DAYS'), (36, '36 DAYS'), (37, '37 DAYS'), (38, '38 DAYS'), (39, '39 DAYS'), (40, '40 DAYS'), (41, '41 DAYS'), (42, '42 DAYS'), (43, '43 DAYS'), (44, '44 DAYS')], default=5),
        ),
        migrations.AlterField(
            model_name='cycledetails',
            name='avg_menstruation_duration',
            field=models.IntegerField(choices=[(1, '1 DAY'), (2, '2 DAYS'), (3, '3 DAYS'), (4, '4 DAYS'), (5, '5 DAYS'), (6, '6 DAYS'), (7, '7 DAYS'), (8, '8 DAYS'), (9, '9 DAYS'), (10, '10 DAYS')], default=30),
        ),
        migrations.AlterField(
            model_name='cycledetails',
            name='last_menstruation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
