# Generated by Django 5.2.6 on 2025-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_core', '0002_cyclewindow_alter_cycledetails_avg_cycle_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycledetails',
            name='avg_cycle_duration',
            field=models.IntegerField(choices=[(22, '22 DAYS'), (23, '23 DAYS'), (24, '24 DAYS'), (25, '25 DAYS'), (26, '26 DAYS'), (27, '27 DAYS'), (28, '28 DAYS'), (29, '29 DAYS'), (30, '30 DAYS'), (31, '31 DAYS'), (32, '32 DAYS'), (33, '33 DAYS'), (34, '34 DAYS'), (35, '35 DAYS'), (36, '36 DAYS'), (37, '37 DAYS'), (38, '38 DAYS'), (39, '39 DAYS'), (40, '40 DAYS'), (41, '41 DAYS'), (42, '42 DAYS'), (43, '43 DAYS'), (44, '44 DAYS')], default=28),
        ),
        migrations.AlterField(
            model_name='cycledetails',
            name='avg_menstruation_duration',
            field=models.IntegerField(choices=[(1, '1 DAY'), (2, '2 DAYS'), (3, '3 DAYS'), (4, '4 DAYS'), (5, '5 DAYS'), (6, '6 DAYS'), (7, '7 DAYS'), (8, '8 DAYS'), (9, '9 DAYS'), (10, '10 DAYS')], default=5),
        ),
    ]
